apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: block-all-egress
  namespace: admin
spec:
  podSelector: {}  # admin 네임스페이스의 모든 Pod에 적용
  policyTypes:
    - Egress
  egress: []  # 모든 Egress 트래픽 차단
