apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: admin-ippool
spec:
  cidr: 10.10.10.0/24
  natOutgoing: false
  ipipMode: Never
  vxlanMode: CrossSubnet
  blockSize: 26
  disabled: false
