apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-nginx
  labels:
    app: admin-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      name: admin-nginx
      labels:
        app: server
    spec:
      containers:
        - name: admin-nginx
          image: bitnami/nginx:latest
          ports:
            - containerPort: 80
